### ISSUE TITLE
purescript-foreign: Variable hasOwnProperty is already exported

### ISSUE THREAD

**Issue by garyb** [Pauan/rollup-plugin-purs#1]
Due to:

https://github.com/purescript/purescript-foreign/blob/e88dae6428b6ed100ee86a7aa6573af1f2bd3b26/src/Data/Foreign/Index.purs#L10

Is it actually an error to export members with names of functions in the `Object` prototype?

**Comment by Pauan** [comment]
No, I don't think it should be an error. I think I know what's causing this bug.
