### ISSUE TITLE
Super Hacky module name: Newline in filename when trying to load the output js

### ISSUE THREAD

**Issue by sloosch** [Pauan/rollup-plugin-purs#10]
Having a module defined like:
````purescript
module Foo
(
bar
)
where
...
````
the "super hacky"-regex fails and tries to load "Foo\n(/index.js".

Replacing the regex at https://github.com/Pauan/rollup-plugin-purs/blob/master/index.js#L109 with:
````javascript
var a = /(?:^|\n|\r\n) *module +([^\s]+)/.exec(file);
````
seems to help.

**Comment by Pauan** [comment]
Thanks! I just released version 1.0.26 which fixes this.
