### ISSUE TITLE
Variable replicate already exists

### ISSUE THREAD

**Issue by cyrbon** [Pauan/rollup-plugin-purs#13]
I have tried it on `0.10.7` ecosystem and it works fine. Compiling the same simple function `main = map (_ + 1) 1..10` on the `0.11.2` ecosystem leads to this error:

```
🚨   (purs plugin) Variable replicate already exists
output/Data.Array/foreign.js (43:8)
41: 
42: // In browsers that have Array.prototype.fill we use it, as it's faster.
43: exports.replicate = typeof Array.prototype.fill === "function" ?
            ^
44:     replicate :
45:     replicatePolyfill;
```

Does rollup-plugin-purs work with a lot of breaking changes introduced in `0.11`? This seems to be somehow related that update, or, at least, to the update to the `purescript-arrays`. I can try other packages on `0.11.2` if that will help to figure out what the issue is.

Going off tangent, the code it generated when I tried it on `0.10.7` looked extremely good with all those sweet optimizations. Nice work!

**Comment by Pauan** [comment]
I plan to test `rollup-plugin-purs` with 0.11 very soon, so that I can iron out any bugs.

Thanks for letting me know!

**Comment by Pauan** [comment]
I don't think this error has anything to do with 0.11, I think it was just a bug in `rollup-plugin-purs` which was triggered by the recent changes to `purescript-arrays`

Version `1.0.36` of `rollup-plugin-purs` fixes this error.

Thanks for the report!
