### ISSUE TITLE
purescript-nullable: Unexpected token

### ISSUE THREAD

**Issue by garyb** [Pauan/rollup-plugin-purs#2]
Looks like a rewrite that needs tweaking:
```
1: export var null = null;
              ^
2:
3: export var nullable = function (a, r, f) {
```

Due to https://github.com/purescript-contrib/purescript-nullable/blob/0d29ea44c734522b34058a9399884f21a830aa1c/src/Data/Nullable.js#L3

**Comment by Pauan** [comment]
This is a bit tricky to fix, since ES6 modules can only export bindings, not values, but I think I know how to fix it.
