### ISSUE TITLE
Why is the entry point in the example config 'src/Main.purs'?

### ISSUE THREAD

**Issue by hdgarrood** [Pauan/rollup-plugin-purs#7]
Since this plugin does not compile PureScript code, would it make sense for entry points to be specified as e.g. `./output/Main/index.js` instead?

**Comment by hdgarrood** [comment]
To clarify - I'm working on integrating this plugin with Pulp, and Pulp can reliably locate the JS file for a given module, but it's harder to reliably location the purescript file for a given module, so it would be easier from Pulp's point of view if we could specify the entry point as the JS file. At the moment, specifying a JS entry point does appear to work, except that no call to main is being generated even with the `runMain` option set.

**Comment by hdgarrood** [comment]
In case you want to take a look: https://github.com/hdgarrood/purescript-rollup

**Comment by Pauan** [comment]
The entry point can be whatever you want it to be, `.purs` or `.js`, so using `./output/Main/index.js` is fine too.

I just need to make a change so that it can run the `main` function of the `.js` file.

Nice work on the Rollup FFI bindings.

**Comment by Pauan** [comment]
I just published version 1.0.8 which fixes `runMain` with `.js` files.

**Comment by hdgarrood** [comment]
Super, thanks! :)
