### ISSUE TITLE
unsafeCompare included despite not being used

### ISSUE THREAD

**Issue by hdgarrood** [Pauan/rollup-plugin-purs#8]
I guess this might really be a Rollup issue, but I'm not sure. I tried bundling the code that you get by running `pulp init` via this plugin using the example config given on the README, and got this:

```javascript
(function () {
  'use strict';

  var unsafeCompareImpl__private_do_not_use_export__0$0__private_do_not_use_uncurried__5__1$0 = function(lt, eq, gt, x, y) {
    return x < y ? lt : x === y ? eq : gt;
  };

  var unsafeCompareImpl__private_do_not_use_export__0$0 = function (lt) {
    return function (eq) {
      return function (gt) {
        return function (x) {
          return function (y) {
            return unsafeCompareImpl__private_do_not_use_export__0$0__private_do_not_use_uncurried__5__1$0(lt, eq, gt, x, y);
          };
        };
      };
    };
  };

  var LT = (function () {
      function LT() {

      }
      LT.value = new LT();
      return LT;
  })();
  var GT = (function () {
      function GT() {

      }
      GT.value = new GT();
      return GT;
  })();
  var EQ = (function () {
      function EQ() {

      }
      EQ.value = new EQ();
      return EQ;
  })();

  var unsafeCompare = unsafeCompareImpl__private_do_not_use_export__0$0(LT.value)(EQ.value)(GT.value);

  var log__private_do_not_use_export__0$0 = function (s) {
    return function () {
      console.log(s);
      return {};
    };
  };

  var main = log__private_do_not_use_export__0$0("Hello sailor!");

  main();
}());
//# sourceMappingURL=bundle.js.map
```

I was expecting the bundle to only contain `log` and `main`. Do you know what's going on here?

**Comment by hdgarrood** [comment]
Similarly, I started with a new project created by `pulp init`, and then ran `bower install --save purescript-maybe`, and modified `src/Main.purs` to look like this:

```purescript
module Main (main) where

import Prelude
import Data.Maybe
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Console (CONSOLE, log)

main :: forall e. Eff (console :: CONSOLE | e) Unit
main = do
  log "Hello sailor!"

somethingElse :: Maybe String
somethingElse = Nothing
```

Note that since `somethingElse` is not exported, we should be able to remove it from the bundle - and this does happen, but a few other unused functions do make it into the bundle, namely the `Maybe` ADT, `isNothing`, `isJust`, `maybe`, and `const`.

**Comment by hdgarrood** [comment]
Oh also this all happened with rollup 0.41.3, rollup-plugin-purs 1.0.8, rollup-plugin-node-resolve 2.0.0.

**Comment by Pauan** [comment]
Yeah, it's a Rollup issue. Basically, [Rollup doesn't understand curried functions](http://rollupjs.org/?version=0.41.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBmb28oeCklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwZnVuY3Rpb24lMjAoeSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIweCUyMCUyQiUyMHklM0IlNUNuJTIwJTIwJTdEJTNCJTVDbiU3RCU1Q24lNUNuZnVuY3Rpb24lMjBiYXIoeCUyQyUyMHkpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHglMjAlMkIlMjB5JTNCJTVDbiU3RCU1Q24lNUNuZm9vKDEpKDIpJTNCJTVDbmJhcigxJTJDJTIwMiklM0IlMjIlN0QlNUQlN0Q=).

**Comment by hdgarrood** [comment]
Ah, right. Do you know if this is being worked on, or if it's something we expect to be fixed at some point? It seems to me like fixing this is a necessity if rollup is going to replace psc-bundle.

**Comment by hdgarrood** [comment]
Also, is the problem in your example that Rollup is unable to determine that `foo` is a pure function and therefore it is not removed from the output bundle?

**Comment by hdgarrood** [comment]
See https://github.com/rollup/rollup/issues/1263.

**Comment by Pauan** [comment]
I've added a custom dead code elimination algorithm, which helps out a lot. This is the new output:

```
(function () {
  'use strict';

  (function () {
    function _LT2() {}
    _LT2.value = new _LT2();
    return _LT2;
  })();

  (function () {
    function _GT2() {}
    _GT2.value = new _GT2();
    return _GT2;
  })();

  (function () {
    function _EQ2() {}
    _EQ2.value = new _EQ2();
    return _EQ2;
  })();

  var _log2 = function (_s) {
    return function () {
      console.log(_s);
      return {};
    };
  };

  var _main = _log2("Hello sailor!");

  _main();
})();
//# sourceMappingURL=bundle.js.map
```

And if you use the `assumePureVars` option (defaults to `true`), then the output is even better:

```
(function () {
  'use strict';

  var _log2 = function (_s) {
    return function () {
      console.log(_s);
      return {};
    };
  };

  var _main = _log2("Hello sailor!");

  _main();
})();
//# sourceMappingURL=bundle.js.map
```

I believe `psc-bundle` already assumes that variable assignment is pure, so `assumePureVars` is essentially using a similar algorithm as `psc-bundle`

**Comment by hdgarrood** [comment]
Nice work!
